version: "3.9"

services:
  backend:
    container_name: llbe
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    command: npx nodemon --legacy-watch server.js

  frontend:
    container_name: llfe
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    command: npm run dev -- --host
    depends_on:
      - backend

volumes:
  backend_node_modules:
  frontend_node_modules:
